### ISSUE TITLE
Map View Filter Problem

### ISSUE THREAD

**Issue by cjt3** [esm7/obsidian-map-view#124]
I have been having a problem with some notes not displaying in Map View with a filter, and also getting an error (red box) on the filter.  I finally tracked it down to it being an issue with any note that has parentheses in the path (either in the note name or folder name).

Example:  I have a note named "Trip (Jan 2022)".  I can display a Map View of that note just fine, but if I try to filter on linkedfrom:"Trip (Jan 2022)" the filter gives an error.

**Comment by esm7** [comment]
Thank you for the precise finding of the root cause, it's indeed an edge case I didn't consider. Will get it fixed.

**Comment by esm7** [comment]
Fixed in 2.3.0 (not released yet).

**Comment by esm7** [comment]
Just a few hours ago :)

**Comment by championswimmer** [comment]
I just updated to 3.0 and still have the same issue 

<img width="336" alt="image" src="https://user-images.githubusercontent.com/1327050/212100541-fbc29eb0-9ad1-4f5d-8ae4-d6c9939aa83e.png">


Red box. 

Logs don't quite say much 

<img width="364" alt="image" src="https://user-images.githubusercontent.com/1327050/212100603-9e109503-b39e-4161-8c3c-5017bdf4cca7.png">


This is my filter query `linkedfrom:"Create/Travel/2022-01 England & Scotland.md" `

Are special characters not allowed in linkedfrom filename? (like `&`) ?

**Comment by esm7** [comment]
I didn't take into account the `&` character. Will release a fix soon (probably tomorrow).

**Comment by esm7** [comment]
Released the fix.
