### ISSUE TITLE
Can't enable the plugin

### ISSUE THREAD

**Issue by nhan000** [esm7/obsidian-map-view#352]
After updating to 6.0.0, I dropped in a GPX file and the track didn't show up. I tested in a sandbox vault, and it worked fine.

In my main vault, I tried disable the Map View plugin, and I couldn't enable it again. I got this notification:

<img width="258" height="42" alt="Image" src="https://github.com/user-attachments/assets/9ad742b6-bb9e-464e-b04e-6185fd81ccad" />

How can I troubleshoot? I have like 100 community plugins so I hope if it's a plugin conflict there's a way to figure out which one causes it.

I'm on Windows 11, Obsidian 1.10.0, installer version 1.9.14.

**Comment by esm7** [comment]
Can you open the Obsidian developer console (Ctrl+Shift+I) and copy what's there?

**Comment by nhan000** [comment]
<img width="1165" height="1149" alt="Image" src="https://github.com/user-attachments/assets/e10028e7-2cf5-41aa-87cb-8e20613fb05a" />

**Comment by esm7** [comment]
Can you try to upgrade to the just-released 6.0.1? I think it should solve the issue.

**Comment by nhan000** [comment]
It still doesn't work

<img width="1173" height="765" alt="Image" src="https://github.com/user-attachments/assets/161b6c81-82f4-4a02-a77d-837fa447e0ba" />

**Comment by esm7** [comment]
Some other plugin of yours registers a view named "map". Can you try to
disable plugins that may be the offending ones?

**Comment by acrobatman** [comment]
When I upgrade to 6.0.2 from 6.0.0 I met the same problem, but it fixed it after I restarted obsidian.

**Comment by nhan000** [comment]
I made a new blank vault. I installed only this plugin, and it seemed to load on first try, but after disabling it I can't enable it again.

Windows 11 25H2. Obsidian 1.10.0, installer version 1.9.14

<img width="728" height="368" alt="Image" src="https://github.com/user-attachments/assets/8b18bf38-d36a-4c20-8885-1d0134900fbc" />

Reverted to 5.5.1 and it worked fine.

**Comment by esm7** [comment]
This seems to be a bug specific to the disable functionality. The plugin does not correctly remove the registration for handling GPX embeds (which is of course new to 6.x), so when re-enabled, it tries to register an embed handler that already exists.
While this should certainly be fixed, if it works well when restarting Obsidian (not part of the disable->enable flow), it does not seem to be related to your original issue, and searching for the other plugin that registers a view named `map` should still be the thing to do.

**Comment by nhan000** [comment]
Sorry I should have added that it still couldn't be enabled even after I closed and reopened Obsidian with the new blank vault. Haven't tried restarting my laptop yet.

> searching for the other plugin that registers a view named map should still be the thing to do

Disabling all other plugins in my main vault didn't help. In the new blank vault, there's no other plugin.

Looks like I'm the only one who has this issue, and I don't need the new features yet, so I'm happy to stick with 5.5.1 for a little while :)

**Comment by esm7** [comment]
That's really weird. I'm currently traveling, so if it's not urgent to you, I'll wait for when I'm back to dig deeper, and if you don't mind, might ask for your help to try out a fix when I have one 🙏

**Comment by nhan000** [comment]
Enjoy your trip! :) There’s absolutely no rush from my side.

**Comment by esm7** [comment]
Hi, any news about this one? Is it still happening in 6.0.3?

**Comment by nhan000** [comment]
It's working now with 6.0.3. Thanks a lot for the fix!

However, if I disabled and reenabled the plugin, I still had the same issue that it couldn't be enabled.

<img width="258" height="42" alt="Image" src="https://github.com/user-attachments/assets/9ad742b6-bb9e-464e-b04e-6185fd81ccad" />

Obviously in normal usage I wouldn't do that. So not really something of concern right now.
